#!/bin/bash

filename="$HOME/.weight"

if [ ! -f "$filename" ]; then
  touch "$filename"
fi

function usage() {
  echo "Usage: $0 <command>"
  echo "Commands:"
  echo "  add <weight> - Add a new weight"
  echo "  edit - edit weight file"
  echo "  help - show this help"
}

if [ $# -eq 0 ]; then
  "$0" add
  exit 1
fi

case "$1" in
  add)
    if [ $# -eq 1 ]; then
      echo "Enter weight:"
      read -r weight
    else
      weight="$2"
    fi

    echo "$(date +"%Y-%m-%d %H:%M:%S")	$(date +%s)	$weight" >> "$filename"
    ;;
  edit)
    "$EDITOR" "$filename"
    ;;
  help)
    usage
    ;;
  *)
    echo "Unknown command: $1"
    exit 1
    ;;
esac
