#!/bin/bash

source /home/sam/.weight_goal

filename="$HOME/.weight"

if [ ! -f "$filename" ]; then
  touch "$filename"
fi

function usage() {
  echo "Usage: $0 <command>"
  echo "Commands:"
  echo "  add <weight> - Add a new weight"
  echo "  graph - show graph"
  echo "  edit - edit weight file"
  echo "  help - show this help"
}

if [ $# -eq 0 ]; then
  "$0" add
  exit 1
fi

case "$1" in
  add)
    if [ $# -eq 1 ]; then
      echo "Enter weight:"
      read -r weight
    else
      weight="$2"
    fi

    echo "$(date +"%Y-%m-%d %H:%M:%S")	$(date +%s)	$weight" >> "$filename"
    tail -n 5 "$filename"
    ;;
  graph)
    tail -n 30 "$filename" > /tmp/weight.txt
    goal_epoch=$(date -d "$goal_date" +%s)
    gnuplot << EOF
set terminal svg size 1024,768 enhanced font 'Verdana,20'
set output '/tmp/weight_graph.svg'

set datafile separator "\t"

# Title and labels
set title "Weight Over Time"
set xlabel "Date"
set ylabel "Weight (lbs)"
set grid
set xdata time
set timefmt "%Y-%m-%d %H:%M:%S"
set format x "%Y-%m-%d"
set xtics rotate by -20

goal(x) = $target_weight

plot '/tmp/weight.txt' \
    using 1:3 title 'Weight' with lines linewidth 2, \
    '/tmp/weight.txt' using 1:(goal(\$2)) title 'Goal' with lines linewidth 2

unset output
EOF
    firefox /tmp/weight_graph.svg
    ;;
  edit)
    "$EDITOR" "$filename"
    ;;
  help)
    usage
    ;;
  *)
    echo "Unknown command: $1"
    exit 1
    ;;
esac
